<div class="page-title col-xs-12">
	<h1>Dashboard</h1>
</div>
<div class="page-body col-xs-12">
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-4">
			<h3><a href="?page=dashboard_users">Users</a></h3>
			<?php echo(count($users)) ?> registered users.
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<h3><a href="?page=dashboard_categories">Categories</a></h3>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<h3><a href="?page=dashboard_items">Items</a></h3>
		</div>
	</div>
</div>