<div class="row">
	<div class="col-md-3">
		<img src="<?=$item->getImage();?>" alt="img" style="max-width:100%">
	</div>
	<div class="col-md-9">
		<h4><?=$item -> getName()?></h4>
		<p><?=$item -> getDescription()?></p>
		<p><?=$item -> getPrice()?> €</p>
	</div>
	<div class="order-add col-xs-12">
		<h4>Add to cart</h4>
		<form action="" method="post">
			<div class="row">
				<fieldset>
					<div class="form-group col-xs-6 col-sm-4 col-md-2">
						<label for="add_qty">Quantity</label>
						<input type="number" class="form-control" name="add_qty" value="1" min="1" max="<?php echo $item -> getStock() ?>">
					</div>
				</fieldset>
				<div class="submit col-xs-6 col-sm-4 col-md-2 text-right">
					<button type="submit" class="btn btn-primary">Add to cart</button>
				</div>
			</div>
		</form>
	</div>
</div>