<div class="page-title col-xs-12">
	<h1>Login</h1>
</div>
<div class="login-form col-xs-12">
	<form action="index.php?page=login" method="POST">
		<div class="row">
			<fieldset>
				<div class="form-group col-xs-12 col-sm-6">
					<label for="login">Login</label>
					<input type="text" class="form-control" placeholder="Login" name="login_login" value="<?=htmlentities($login)?>">
				</div>
				<div class="form-group col-xs-12 col-sm-6">
					<label for="password">Password</label>
					<input type="password" class="form-control" placeholder="Password" name="login_password">
				</div>
			</fieldset>
		</div>
		<div class="row">
			<div class="submit col-xs-12 text-right">
				<button type="submit" class="btn btn-success">Login</button>
			</div>
		</div>
	</form>
</div>
