<nav class="nav navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="?page=home">
				<img src="http://vignette3.wikia.nocookie.net/theamazingworldofgumball/images/d/dd/Logo_Dota_2.png/revision/latest?cb=20130329094246" alt="Brand" height="27px"/>
				<!-- <img src="http://s.navi-gaming.com/images/twop/category_icons/d2.png" alt="Brand"/> -->
			</a>
		</div>

		<div class="collapse navbar-collapse" id="navbar">
			<?php require('apps/nav_user.php'); ?>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>
