<ul class="nav navbar-nav">
	<li><a href="?page=categories">Categories</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
	<?php if ($currentUser -> getStatus() > 0)
	{ ?>
		<li><a href="?page=dashboard">Dashboard</a></li>
	<?php } ?>
	<li><a href="?page=basket">My basket</a></li>
	<li><a href="?page=profil&id=<?=$_SESSION['id']?>">My profile</a></li>
	<li><a href="?page=logout">Logout</a></li>
</ul>